import type { Metadata } from "next";

import HeaderComponent from "@/components/organisms/HeaderComponent";
import CarrouselHomepage from "@/components/organisms/CarrouselHomepage";
import FooterBooking from "@/components/organisms/FooterBooking";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebpageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <HeaderComponent />
      { children }
      <FooterBooking />
    </main>
  );
}
